voting_system/urls.py
from django.contrib import admin
# from Data_Interaction.admin import admin_site
from django.urls import path

from account.views import *
from account_voting.views import *
from account_administrator.views import *
from rest_framework.routers import DefaultRouter,SimpleRouter
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

from django.urls import re_path,path


from django.views.generic.base import TemplateView
from django.conf.urls.static import serve

from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/login/',log_in,name='log_in'),
    path('account/register/',register,name='register'),
    path('account/accuracy-otp/',Accuracy_otp,name='Accuracy_otp'),
    path('logout/', logout_view, name='logout_view'),
    path('change-password/',change_password,name='change_password'),
    path('update-user-account/',update_user_account,name='update_user_account'),

    # Trang bầu chọn
    path('voting/',voting_page,name='voting_page'),
    path('voted/',voted_page,name='voted_page'),
    path('vote-to/',vote_to,name='vote_to'),
    path('resend-code/',resend_code,name='resend_code'),

    # Trang người đi bầu
    path('administrator/voters/',admin_voters,name='admin_voters'),
    path('administrator/voters/create',admin_create_voters,name='admin_create_voters'),
    path('administrator/voters/update',admin_update_voters,name='admin_update_voters'),
    path('administrator/voters/delete/<int:id_record>/', admin_delete_voters,name='admin_delete_voters'),
    #Trang vị trí
    path('administrator/',admin_page,name='admin_page'),
    path('administrator/positions/',admin_positions,name='admin_positions'),
    path('administrator/positions/create',admin_create_positions,name='admin_create_positions'),
    path('administrator/positions/update',admin_update_positions,name='admin_update_positions'),
    path('administrator/positions/delete/<int:id_record>/', admin_delete_positions,name='admin_delete_positions'),
    # Trang ứng viên
    path('administrator/candidate/',admin_candidate,name='admin_candidate'),
    path('administrator/candidate/create',admin_create_candidate,name='admin_create_candidate'),
    path('administrator/candidate/update',admin_update_candidate,name='admin_update_candidate'),
    path('administrator/candidate/delete/<int:id_record>/', admin_delete_candidate,name='admin_delete_candidate'),

    path('administrator/votes/',admin_votes,name='admin_votes'),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account_administrator/models.py
from django.db import models

# Create your models here.

account_voting/models.py
from django.db import models
from account.models import Account
# Create your models here.

class Position(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Candidate(models.Model):
    fullname = models.CharField(max_length=50)
    photo = models.ImageField(upload_to="candidates")
    bio = models.TextField()
    positions = models.ManyToManyField(Position, related_name='candidates')

    def __str__(self):
        return self.fullname


class Votes(models.Model):
    voter = models.ForeignKey(Account, on_delete=models.CASCADE)
    position = models.ForeignKey(Position, on_delete=models.CASCADE,related_name='positionss')
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)

account_administrator/views.py
from .models import *
from account_voting.models import *

from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_list_or_404, get_object_or_404
from django.core.paginator import Paginator


from django.http import HttpResponse
import requests
import time

from django.db import models
from django.utils import timezone

import os

from datetime import datetime

from django.shortcuts import redirect

from django.contrib.postgres.search import TrigramSimilarity
from django.db.models import Q
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from account.models import *



# Chọn ngôn ngữ//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
def set_Domain():
        Domain = 'http://127.0.0.1:8000'
        return Domain

def set_Page():
	Page = 2
	return Page

def admin_page(request):
    Domain = set_Domain()
    Number_Account = Account.objects.all()
    Number_Position = Position.objects.all()
    Number_Candidate = Candidate.objects.all()
    Number_Votes = Votes.objects.all()

    chart_data = []
    for i in Number_Position:
        chart_data.append({'name_char':i,'labels':i.candidates.all(),'values':[]})
        print(i.candidates.all())

    for j in chart_data:
        for m in  j['labels']:
            j['values'].append(len(Votes.objects.filter(position=j['name_char'],candidate=m)))

    for k in chart_data:
        k['name_char'] = k['name_char'].name
        aa = []
        for l in k['labels']:
            aa.append(l.fullname)
        k['labels'] = aa


    print('chart_data:',chart_data)

    if request.user.is_authenticated:
        if request.user.is_staff:  # Kiểm tra xem người dùng có thuộc nhóm admin hay không
            context = {'Domain':Domain,'name_account':str(request.user.first_name)+' '+str(request.user.last_name)}
            context['Number_Account'] = Number_Account
            context['Number_Position'] = Number_Position
            context['Number_Candidate'] = Number_Candidate
            context['Number_Votes'] = Number_Votes
            context['chart_data'] = chart_data
            print(context)
            return render(request, 'account_administrator/admin.html', context, status=200)
        else:
            return redirect(reverse('voting_page'))  
    else:
        return redirect(reverse('log_in')) 
    
def admin_voters(request):
    Domain = set_Domain()

    # Kiểm tra xem người dùng đã đăng nhập chưa
    if request.user.is_authenticated:
        if request.user.is_staff:  # Kiểm tra xem người dùng có thuộc nhóm admin hay không
            List_Account = Account.objects.all()
            context = {'Domain':Domain,'List_Account':List_Account,'name_account':str(request.user.first_name)+' '+str(request.user.last_name)}
            print(context)
            return render(request, 'account_administrator/admin_voters.html', context, status=200)
        else:
            return redirect(reverse('voting_page'))  # Chuyển hướng tới trang admin
    else:
        return redirect(reverse('log_in'))  # Chuyển hướng tới trang admin
    
def admin_create_voters(request):
    Page = set_Page()
    Domain = set_Domain()

    # Kiểm tra xem người dùng đã đăng nhập chưa
    if request.user.is_authenticated:
        if request.user.is_staff:  # Kiểm tra xem người dùng có thuộc nhóm admin hay không
            if request.method == 'POST':
                fullname = request.POST.get('fullname')
                photo = request.FILES.get('photo')
                bio = request.POST.get('bio')
                position = request.POST.get('position')
                Candidate.objects.create(fullname=fullname,photo=photo,bio=bio,position=Position.objects.get(pk=position))
                
                # Thực hiện chuyển hướng sau khi thêm bản ghi thành công
                return redirect('admin_create_candidate')

            # Nếu là yêu cầu GET hoặc sau khi chuyển hướng, thực hiện hiển thị danh sách vị trí
            List_Position = Position.objects.all()
            List_Candidate = Candidate.objects.all()
            print('List_Candidate:',List_Candidate)
            context = {'Domain':Domain,'List_Candidate':List_Candidate,'List_Position':List_Position,'name_account':str(request.user.first_name)+' '+str(request.user.last_name)}
            print(context)
            return render(request, 'account_administrator/admin_candidate.html', context, status=200)
        else:
            return redirect(reverse('voting_page'))  # Chuyển hướng tới trang admin
    else:
        return redirect(reverse('log_in'))
        
def admin_update_voters(request):
    Domain = set_Domain()

    # Kiểm tra xem người dùng đã đăng nhập chưa
    if request.user.is_authenticated:
        if request.user.is_staff:  # Kiểm tra xem người dùng có thuộc nhóm admin hay không
            if request.method == 'POST':
                id =  request.POST.get('Editid')
                fullname = request.POST.get('fullname')
                photo = request.FILES.get('photo')
                bio = request.POST.get('bio')
                position = request.POST.get('position')

                pr = Candidate.objects.get(pk=id)

                pr.fullname = fullname
                pr.bio = bio
                pr.position = Position.objects.get(pk=position)
                if photo:
                    pr.photo = photo
                    pr.save()
                pr.save()
                # Thực hiện chuyển hướng sau khi thêm bản ghi thành công
                return redirect('admin_update_candidate')

            # Nếu là yêu cầu GET hoặc sau khi chuyển hướng, thực hiện hiển thị danh sách vị trí
            List_Account = Account.objects.all()
            context = {'Domain':Domain,'List_Account':List_Account,'name_account':str(request.user.first_name)+' '+str(request.user.last_name)}
            print(context)
            return render(request, 'account_administrator/admin_voters.html', context, status=200)
        else:
            return redirect(reverse('voting_page'))  # Chuyển hướng tới trang admin
    else:
        return redirect(reverse('log_in'))
        
def admin_delete_voters(request,id_record):
    Domain = set_Domain()
    print('id_record:',id_record)

    # Kiểm tra xem người dùng đã đăng nhập chưa
    if request.user.is_authenticated:
        if request.user.is_staff:  # Kiểm tra xem người dùng có thuộc nhóm admin hay không
            try:
                pr = Account.objects.get(pk=id_record)
                pr.delete()
            except:
                print('thai')
            List_Account = Account.objects.all()
            context = {'Domain':Domain,'List_Account':List_Account,'name_account':str(request.user.first_name)+' '+str(request.user.last_name)}
            print(context)
            return render(request, 'account_administrator/admin_voters.html', context, status=200)
        else:
            return redirect(reverse('voting_page'))  # Chuyển hướng tới trang admin
    else:
        return redirect(reverse('log_in'))  # Chuyển hướng tới trang admin

                
def admin_positions(request):
    Domain = set_Domain()

    # Kiểm tra xem người dùng đã đăng nhập chưa
    if request.user.is_authenticated:
        if request.user.is_staff:  # Kiểm tra xem người dùng có thuộc nhóm admin hay không
            List_Position = Position.objects.all()
            context = {'Domain':Domain,'List_Position':List_Position,'name_account':str(request.user.first_name)+' '+str(request.user.last_name)}
            print(context)
            return render(request, 'account_administrator/admin_positions.html', context, status=200)
        else:
            return redirect(reverse('voting_page'))  
    else:
        return redirect(reverse('log_in'))  
def admin_create_positions(request):
    Domain = set_Domain()

    # Kiểm tra xem người dùng đã đăng nhập chưa
    if request.user.is_authenticated:
        if request.user.is_staff:  # Kiểm tra xem người dùng có thuộc nhóm admin hay không
            if request.method == 'POST':
                name = request.POST.get('name')
                Position.objects.create(name=name)
                
                # Thực hiện chuyển hướng sau khi thêm bản ghi thành công
                return redirect('admin_create_positions')

            # Nếu là yêu cầu GET hoặc sau khi chuyển hướng, thực hiện hiển thị danh sách vị trí
            List_Position = Position.objects.all()
            context = {'Domain': Domain, 'List_Position': List_Position, 'name_account': str(request.user.first_name) + ' ' + str(request.user.last_name)}
            print(context)
            return render(request, 'account_administrator/admin_positions.html', context, status=200)
        else:
            return redirect(reverse('voting_page'))  # Chuyển hướng tới trang admin
    else:
        return redirect(reverse('log_in'))
        
def admin_update_positions(request):
    Page = set_Page()
    Domain = set_Domain()

    # Kiểm tra xem người dùng đã đăng nhập chưa
    if request.user.is_authenticated:
        if request.user.is_staff:  # Kiểm tra xem người dùng có thuộc nhóm admin hay không
            if request.method == 'POST':
                name = request.POST.get('Editname')
                id =  request.POST.get('Editid')
                pr = Position.objects.get(pk=id)
                pr.name = name
                pr.save()
                # Thực hiện chuyển hướng sau khi thêm bản ghi thành công
                return redirect('admin_update_positions')


account_administrator/templates/account_administrator/admin_candidate.html
{% extends "account_administrator/base.html" %}
{% block content %}
<section class="content-header">
    <h1>
        Ứng viên bình chọn
    </h1>
    <!-- <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Candidates</li>
    </ol> -->
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <a data-toggle="modal" class="btn btn-success btn-sm btn-flat create_candidate"><i
                            class="fa fa-plus"></i>Thêm mới</a>
                </div>
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-hover table-striped">
                        <thead style="background-color: #222D32; color:white;">
                            <th>Tên đầy đủ</th>
                            <th>VỊ trí ứng cử</th>
                            <th>Mô tả</th>
                            <th>Ảnh đại diện</th>
                            <th>Hoạt động</th>
                        </thead>
                        <tbody>
                            {% for i in List_Candidate %}
                            <tr>
                                <td>{{i.fullname}}</td>
                                <td style="display: flex; flex-direction: column;">
                                    <ul>
                                        {% for j in i.positions.all %}
                                        <li>{{j.name}}</li>
                                        {% endfor %}
                                    </ul>
                                </td>
                                <td>{{i.bio}}</td>
                                <td><img src="{{Domain}}/{{i.photo}}" width="80" height="80" alt="{{i.fullname}}"
                                        class="img img-fluid"></td>
                                <td>
                                    <button class='btn btn-primary btn-sm edit btn-flat update_candidate'
                                        data-id='{{ i.id }}' data-fullname='{{ i.fullname}}' data-bio='{{ i.bio }}'
                                        data-positions='[{% for position in i.positions.all %}"{{ position.id }}"{% if not forloop.last %},{% endif %}{% endfor %}]'><i
                                            class='fa fa-edit'></i> Cập
                                        nhật</button>
                                    <a href="{% url 'admin_delete_candidate' i.id %}"
                                        class='btn btn-primary btn-sm  btn-flat'><i class='fa fa-trash'></i> Xóa</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Bang position create -->
<div class="modal fade create_C">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><b>Thêm mới Ứng viên</b></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" enctype="multipart/form-data" method="POST"
                    action="{% url 'admin_create_candidate' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="form-group has-feedback">
                            <span class="text-danger"></span>
                            <label for="id_fullname">Tên đầy đủ:</label>
                            <input type="text" name="fullname" maxlength="50" class="form-control" required
                                id="id_fullname">
                        </div>
                        <div class="form-group has-feedback">
                            <span class="text-danger"></span>
                            <label for="id_bio">Mô tả:</label>
                            <textarea name="bio" cols="40" rows="10" class="form-control" required
                                id="id_bio"></textarea>
                        </div>
                        <div class="form-group has-feedback">
                            <span class="text-danger"></span>
                            <label for="id_position">Vị trí:</label>
                            <select name="position" class="form-control" required id="id_position" multiple>
                                {% for i in List_Position %}
                                <option value="{{i.id}}">{{i.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group has-feedback">
                            <span class="text-danger"></span>
                            <label for="id_photo">Ảnh đại diện:</label>
                            <input type="file" name="photo" accept="image/*" class="form-control" required
                                id="id_photo">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger btn-flat pull-left" data-dismiss="modal"><i
                                class="fa fa-close"></i> Đóng </button>
                        <button type="submit" class="btn btn-success btn-flat" name="add"><i class="fa fa-save"></i>
                            Lưu</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- end -->
<!-- Edit -->
<div class="modal fade update_C">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><b>Cập nhật ứng viên:</b></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" enctype="multipart/form-data" method="POST"
                    action="{% url 'admin_update_candidate' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="form-group has-feedback" style="display: none;">
                            <span class="text-danger"></span>
                            <label for="id_id">ID:</label>
                            <input type="text" name="Editid" maxlength="50" class="form-control" required id="id_id">
                        </div>
                        <div class="form-group has-feedback">
                            <span class="text-danger"></span>
                            <label for="id_fullname">Họ tên ứng viên:</label>
                            <input type="text" name="fullname" maxlength="50" class="form-control" required
                                id="id_fullname_C">
                        </div>
                        <div class="form-group has-feedback">
                            <span class="text-danger"></span>
                            <label for="id_bio">Mô tả:</label>
                            <textarea name="bio" cols="40" rows="10" class="form-control" required
                                id="id_bio_C"></textarea>
                        </div>
                        <div class="form-group has-feedback">
                            <span class="text-danger"></span>
                            <label for="id_position">Vị trí:</label>
                            <select name="position" class="form-control" required id="id_positions_C" multiple>
                                {% for i in List_Position %}
                                <option value="{{i.id}}" selected>{{i.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group has-feedback">
                            <span class="text-danger"></span>
                            <label for="id_photo">Hình ảnh:</label>
                            <input type="file" name="photo" accept="image/*" class="form-control" id="id_photo_C">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger btn-flat pull-left" data-dismiss="modal"><i
                                class="fa fa-close"></i> Đóng </button>
                        <button type="submit" class="btn btn-success btn-flat" name="add"><i class="fa fa-save"></i>
                            Lưu</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- end -->
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(function () {
        $(document).on('click', '.create_candidate', function (e) {
            e.preventDefault();
            $('.create_C').modal('show');
        });
        $(document).on('click', '.update_candidate', function (e) {
            e.preventDefault();
            $('.update_C').modal('show');
            var id = $(this).data('id');
            var fullname = $(this).data('fullname');
            var bio = $(this).data('bio');
            var position = $(this).data('positions');
            $('#id_fullname_C').val(fullname);
            $('#id_bio_C').val(bio);
            $('#id_positions_C').val(position);
            $('#id_id').val(id);
        });
    });
</script>
{% endblock content %}

account_administrator/templates/account_administrator/admin_positions.html
{% extends "account_administrator/base.html" %}
{% block content %}
<section class="content-header">
    <h1>
        Vị trí bình chọn
    </h1>
    <!-- <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Positions</li>
    </ol> -->
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <a href="#addnew" data-toggle="modal" class="btn btn-success btn-sm btn-flat"><i
                            class="fa fa-plus"></i> Thêm mới</a>
                </div>
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-hover table-striped">
                        <thead style="background-color: #222D32; color:white;">
                            <th>Tên vị trí</th>
                            <th>Số phiếu đã bầu</th>
                            <th>Hoạt động</th>
                        </thead>
                        <tbody>
                            {% for i in List_Position %}
                            <tr>
                                <td>{{i.name}}</td>
                                <td>{{ i.positionss.count }}</td>
                                <td>
                                    <a class='btn btn-primary btn-sm  btn-flat edit_positions' data-id='{{ i.id }}'
                                        data-name='{{ i.name }}'><i class='fa fa-edit'></i> Cập nhật</a>
                                    <a href="{% url 'admin_delete_positions' i.id %}"
                                        class='btn btn-primary btn-sm  btn-flat'><i class='fa fa-trash'></i>
                                        Xóa</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Bang position create -->
<div class="modal fade" id="addnew">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><b>Thêm mới vị trí bình chọn</b></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" enctype="multipart/form-data" method="POST"
                    action="{% url 'admin_create_positions' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="form-group has-feedback">
                            <span class="text-danger"></span>
                            <label for="id_fullname">Tên vị trí:</label>
                            <input type="text" name="name" maxlength="50" class="form-control" required
                                id="id_fullname">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger btn-flat pull-left" data-dismiss="modal"><i
                                class="fa fa-close"></i> Đóng </button>
                        <button type="submit" class="btn btn-success btn-flat" name="add"><i class="fa fa-save"></i>
                            Lưu</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- end -->
<!-- Edit -->
<div class="modal fade editModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><b>Cập nhật vị trí</b></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" enctype="multipart/form-data" method="POST"
                    action="{% url 'admin_update_positions' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <div class="form-group has-feedback" style="display:none;">
                            <span class="text-danger"></span>
                            <label for="id_fullname">ID:</label>
                            <input type="text" id="editId" name="Editid" maxlength="50" class="form-control" required>
                        </div>
                        <div class="form-group has-feedback">
                            <span class="text-danger"></span>
                            <label for="id_fullname">Tên vị trí:</label>
                            <input type="text" id="editName" name="Editname" maxlength="50" class="form-control"
                                required>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger btn-flat pull-left" data-dismiss="modal"><i
                                class="fa fa-close"></i> Đóng </button>
                        <button type="submit" class="btn btn-success btn-flat" name="add"><i class="fa fa-save"></i>
                            Lưu</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- end -->
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(function () {
        $(document).on('click', '.edit_positions', function (e) {
            e.preventDefault();
            $('.editModal').modal('show');
            var id = $(this).data('id');
            var name = $(this).data('name');
            $('#editName').val(name);
            $('#editId').val(id);
        });
    });
</script>
{% endblock content %}

account_administrator/templates/account_administrator/admin_votes.html
{% extends "account_administrator/base.html" %}
{% block content %}
<section class="content-header">
    <h1>
        Phiếu bầu
    </h1>
    <!-- <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Votes</li>
    </ol> -->
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <!-- <div class="box-header with-border">
                    <a href="#reset" data-toggle="modal" class="btn btn-danger btn-sm btn-flat"><i
                            class="fa fa-refresh"></i> Reset</a>
                </div> -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-hover table-striped">
                        <thead style="background-color: #222D32; color:white;">
                            <th>Người bỏ phiếu</th>
                            <th>Ứng viên</th>
                            <th>Vị trí</th>
                        </thead>
                        <tbody>
                            {% for i in List_Votes %}
                            <tr>
                                <td>{{ i.voter.first_name }} {{ i.voter.last_name }}</td>
                                <td>{{i.candidate}}</td>
                                <td>{{i.position}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}